swagger: '2.0'
info:
  title: 'Tasks API'
  description: 'This api provides a list of tasks in JSON format'
  version: 1.0.0
host: 'localhost:3333'
paths:
  /api/tasks:
    get:
      summary: Returns a list of tasks
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                  example: '61e16f0e8241ec78fe1f995f'
                title:
                  type: string
                  example: 'Hello, world!'
                description:
                  type: string
                  example: 'This is a sample task.'
                completed:
                  type: boolean
                  example: false
                created_at:
                  type: string
                  example: '2022-01-14T12:39:42.018Z'
        500:
          description: INTERNAL SERVER ERROR
          schema:
            type: object
            properties:
              message:
                type: string
                example: 'Something went wrong'
              error:
                type: string
                example: 'Line 3 col 2'
  /api/tasks/{id}:
    get:
      summary: Returns a single task
      parameters:
        - in: path
          name: id
          required: true
          type: string
          description: Task unique identifier
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              id:
                type: string
                example: '61e16f0e8241ec78fe1f995f'
              title:
                type: string
                example: 'Hello, world!'
              description:
                type: string
                example: 'This is a sample task.'
              completed:
                type: boolean
                example: false
              created_at:
                type: string
                example: '2022-01-14T12:39:42.018Z'
